default_job = "run"
env.CARGO_TERM_COLOR = "always"

[jobs.check]
command = ["cargo", "check"]
need_stdout = false

[jobs.run]
command = ["cargo", "run", "--bin", "blatten-api"]
need_stdout = true
allow_warnings = true
background = false
on_change_strategy = "kill_then_restart"
